/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.DBManager;
import models.HeatPump;
import models.ReplacementPart;
import models.SolarPanel;
import models.Staff;

import utils.EcoPalette;
import utils.ThemeManager;

import views.base.BaseFrame;

/**
 *  AddProduct
 * Allows staff to add a new product to the database.
 *
 * This screen follows the BaseFrame architecture:
 *  - Header + Footer added automatically
 *  - EcoPalette + ThemeManager styling
 *  - Clean separation of UI and logic
 *
 * @author 30246196
 */
public class AddProduct extends BaseFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddProduct.class.getName());

    private Staff loggedInStaff;// the staff logged-in , fix imports
    /**
     * Creates new form AddProduct
     */
    public AddProduct(Staff staff) {
        super(); // BaseFrame → header, footer, background
        initComponents();
        
        applyCommonTheme(); // headings
        applyViewTheme(); // list + muted text
        applyThemeStyles(); // buttons
    }

    //Theme Methods
    
    @Override
    protected void applyCommonTheme()
    {
        super.applyCommonTheme();
        ThemeManager.styleHeading(lblAddProduct);
    }
    
    private void applyThemeStyles()
    {
        ThemeManager.stylePrimary(btnAddProduct);
        ThemeManager.styleBackButton(btnBack);
    }
    
    private void applyViewTheme()
    {
        //  colour text fields
        txtProductName.setBackground(EcoPalette.DUCK_EGG);
        txtPrice.setBackground(EcoPalette.DUCK_EGG);
        txtStock.setBackground(EcoPalette.DUCK_EGG);
        cmbProductType.setBackground(EcoPalette.DUCK_EGG);
        txtExtraAttribute.setBackground(EcoPalette.DUCK_EGG);
    }
    
    // Dynamic label for extra attribute: 
//    private void setupDynamicLabel()
//    {
//        cmbProductType.addActionListener(e -> {
//            String type = (String) cmbProductType.getSelectedItem();
//            
//            switch (type)
//            {
//                case "Solar Panel": lblExtraAttribute.setText("Wattage Output");
//                break;
//                
//                case "Heat Pump": lblExtraAttribute.setText("Efficiency Rating");
//                break;
//                
//                case "Replacement Part": lblExtraAttribute.setText("Part For");
//                break;
//            }
//        });
//    }
    
    
    // Method Add Product
    
//    private void addProduct()
//    {
//        try{
//            // Read values from fields
//            String name = txtProductName.getText().trim();
//            double price = Double.parseDouble(txtPrice.getText().trim());
//            int stock = Integer.parseInt(txtStock.getText().trim());
//            String type = (String)cmbProductType.getSelectedItem();
//            String extra =
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrice = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        lblAddProduct = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        txtExtraAttribute = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblExtraAttribute = new javax.swing.JLabel();
        blbProductId = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        lblProductName = new javax.swing.JLabel();
        cmbProductType = new javax.swing.JComboBox<>();
        cmbPartFor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStock.setText("Stock Level:");

        lblAddProduct.setText("ADD PRODUCT DETAILS");

        lblPrice.setText("Price");

        lblStaff.setText(" by Staff");

        btnAddProduct.setText("ADD NEW PRODUCT");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblExtraAttribute.setText("Extra Attribute ");

        blbProductId.setText("Product ID");

        lblType.setText("Type of Product");

        txtProductId.setEditable(false);

        lblProductName.setText("Product Name");

        cmbProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heat Pump", "Solar Panel", "Replacement Part", " " }));
        cmbProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductTypeActionPerformed(evt);
            }
        });

        cmbPartFor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heat Pump\t", "Solar Panel", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddProduct)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblExtraAttribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blbProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cmbProductType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbPartFor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtExtraAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(btnBack)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct)
                    .addComponent(lblStaff))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blbProductId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblExtraAttribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProductId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProductName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExtraAttribute)
                            .addComponent(cmbPartFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnBack))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        //edit a product from Products table in the db

        // define and get the values from the text:
        String productName= txtProductName.getText( );
        double price = Double.parseDouble(txtPrice.getText());
        int stockLevel = Integer.parseInt(txtStock.getText());
        //String productType = cmbProductType.getSelectedItem();// todo add productType
        String extra = txtExtraAttribute.getText();

        // getters and setters added to Product

        // assign the modified values
//        newProduct.setProductName(productName);
//        newProduct.setPrice(price);
//        newProduct.setStockLevel(stockLevel);
//        newProduct.setProductType(productType);
//
//        // add the extra Attribute in the corespondent : SolaPanel, Heat Pump or Replacement Part
//        newProduct.setExtraAttribute(extra);
//
//        DBManager db = new DBManager();
//
//        // Product types: SolarPanel, Heat Pump and Replacement Part
//        switch(newProduct.getProductType())
//        {
//            case "Solar Panel":

//            SolarPanel sp = (SolarPanel)newProduct;
//
//            int wattageOutput = Integer.parseInt(txtExtraAttribute.getText());
//            sp.setWattageOutput(wattageOutput);
//
//            //DBManager db = new DBManager();// Create a new DBManager instance to interact with the database.
//            db.editProduct(sp);// create editProduct method in DBManager
//
//            break;
//
//            case "Heat Pump":

//            HeatPump hp = (HeatPump)newProduct;
//
//            double efficiencyRating = Double.parseDouble(txtExtraAttribute.getText());
//            hp.setEfficiencyRating(efficiencyRating);
//
//            //DBManager db = new DBManager();
//            db.editProduct(hp);
//
//            break;
//
//            case "Replacement Part":
//
//            ReplacementPart rp = (ReplacementPart)newProduct;
//
//            String partFor = txtExtraAttribute.getText();
//            rp.setPartFor(partFor);
//
//            //DBManager db = new DBManager();
//            db.editProduct(rp);
//            break;
//        }

        // TODO create modifyProduct(product)

        // TODO Show Confirmation frame/page

        // TODO Display confirmation modify frame

    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //return to ModifyProductForStaff
        AddProduct addProd = new AddProduct(loggedInStaff);// added by ne in stage 6
        addProd.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AddProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbProductId;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbPartFor;
    private javax.swing.JComboBox<String> cmbProductType;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblExtraAttribute;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtExtraAttribute;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
