/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.Map;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.DBManager;
import models.Order;
import models.OrderLine;
import utils.ThemeManager;
import views.base.BaseFrame;

/**
 *
 * @author 30246196
 */
public class Basket extends BaseFrame { 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Basket.class.getName());

    // Declaration of currentOrder and loggedInCustomer
    private Order currentOrder;
    private Customer loggedInCustomer;//fix imports
    
    /**
     * Creates new form Basket
     * @param currentOrder
     */
    public Basket(Customer c,Order o)// fix imports
    {
        loggedInCustomer = c;
        currentOrder = o;
        
        //setTitle("Customer Home"); // set title
        initComponents();
        
        // resize the columns of the Basket table
        tblProductBasket.setAutoResizeMode(WIDTH); 
        
        applyCommonTheme(); // adds HeaderBar + background
        applyThemeStyles();// styles buttons, labels, etc.
        
        // check with a  customised welcome:
        lblWelcomeBasket.setText("This is your basket, " + loggedInCustomer.getFirstName());
        
        DefaultTableModel productBasketModel = (DefaultTableModel)tblProductBasket.getModel();
        // entrySet convert a hashmap into smth readable
        for(Map.Entry<Integer,OrderLine> olMapEntry : currentOrder.getOrderLines().entrySet())// fix imports
        {
            OrderLine actualOrderLine = olMapEntry.getValue();
           //put into the table in a list first
           productBasketModel.addRow(new Object[]
           {
                   // 
                actualOrderLine.getProduct().getProductId(),// TODO
                actualOrderLine.getProduct().getProductName(),
                actualOrderLine.getProduct().getPrice(),
                actualOrderLine.getQuantity()//
                  // create getQuantity() method
            } );
            
         tblProductBasket.setModel(productBasketModel);
        }
        
    }
    
    // Method apply Theme Style customised to this page;
    private void applyThemeStyles()
    {
        ThemeManager.styleHeading(lblWelcomeBasket);
        ThemeManager.stylePrimary(btnAddMoreProducts);
        ThemeManager.styleSecondary(btnBuy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductBasket = new javax.swing.JTable();
        btnAddMoreProducts = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        lblWelcomeBasket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProductBasket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "Product", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductBasket);

        btnAddMoreProducts.setText("ADD MORE PRODUCTS");
        btnAddMoreProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoreProductsActionPerformed(evt);
            }
        });

        btnBuy.setText("BUY");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        lblWelcomeBasket.setText("This is your basket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddMoreProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnBuy))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblWelcomeBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblWelcomeBasket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMoreProducts)
                    .addComponent(btnBuy))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMoreProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoreProductsActionPerformed
        // Go back to product selection screen
        ShopPageForCustomers shop = new ShopPageForCustomers(loggedInCustomer, currentOrder);
        shop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddMoreProductsActionPerformed

    // button Buy pressed
    // Saves the order to the database 
    // transitions the user to an Confirmation screen/page.
    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // Create a new DBManager instance to interact with the database.
        DBManager db = new DBManager();//fix imports
        
        // Save the current order to the database
        // uses the logged-in Customer's Username as identifier
        db.writeOrder(currentOrder,loggedInCustomer.getUsername());
        
//        // Show the Confirmation page (previous stage)
//        Confirmation conf = new Confirmation(loggedInCustomer);
//        
//        // display the confirmation frame
//        conf.setVisible(true);
//        this.setVisible(false);
        //dispose(); //  close current frame
        
        //stage 11 go to SelectMethodPayment view
        SelectPaymentMethod selPayment =new SelectPaymentMethod(currentOrder,loggedInCustomer);
        
        // display the SelectMethodPayment view
        selPayment.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Basket(currentOrder).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoreProducts;
    private javax.swing.JButton btnBuy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcomeBasket;
    private javax.swing.JTable tblProductBasket;
    // End of variables declaration//GEN-END:variables
}
