/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import models.Customer;
import models.DBManager;
import utils.ThemeManager;
import views.base.BaseFrame;

/**
 *
 * @author 30246196
 */
public class ChangeAddress extends BaseFrame {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangeAddress.class.getName());
    
    //private final String username;
    private final Customer loggedInCustomer;
    private final DBManager db = new DBManager();

    /*
    * 
    * A view that lets a Customer update their address details.
    *   Read-only: FirstName, LastName.
    *   Editable: AddressLine1, AddressLine2, Town, Postcode.
    */
    public ChangeAddress(Customer customer) {
        // pass customer 
        this.loggedInCustomer = customer;
         
        setTitle("GLASGOW GREEN ENERGY");
        initComponents();
        applyCommonTheme(); // adds HeaderBar
        applyThemeStyles(); // styles buttons + fields
        loadCustomer(); // loads existing address
    }    
      
    //Method apply Theme Styles
    private void applyThemeStyles()
    {
        ThemeManager.stylePrimary(btnModify);
        ThemeManager.styleSecondary(btnBack);
        txtAddress1.setPreferredSize(new java.awt.Dimension(250, 28));
        txtAddress2.setPreferredSize(new java.awt.Dimension(250, 28));
        txtTown.setPreferredSize(new java.awt.Dimension(250, 28));
        txtPostcode.setPreferredSize(new java.awt.Dimension(250, 28));
    }
    

    //Method load the logged In Customer
    
    private void loadCustomer()
    {
            if (loggedInCustomer == null) return;
            txtFirstName.setText(loggedInCustomer.getFirstName());
            txtLastName.setText(loggedInCustomer.getLastName());
            txtAddress1.setText(safe(loggedInCustomer.getAddressLine1()));
            txtAddress2.setText(safe(loggedInCustomer.getAddressLine2()));
            txtTown.setText(safe(loggedInCustomer.getTown()));
            txtPostcode.setText(safe(loggedInCustomer.getPostcode()));
    }
    
    //Method to get the string "" (empty when there is null in the field in the db
    
    private static String safe(String s)
    {
        return s == null ? "" : s;
    }
    
    
private void onModify() {
        try {
            String address1 = txtAddress1.getText().trim();
            String address2 = txtAddress2.getText().trim();
            String town     = txtTown.getText().trim();
            String postcode = txtPostcode.getText().trim();

            // Basic validation
            if (address1.isEmpty()) throw new IllegalArgumentException("Address Line 1 is required.");
            if (town.isEmpty())     throw new IllegalArgumentException("Town is required.");
            if (postcode.isEmpty()) throw new IllegalArgumentException("Postcode is required.");

            boolean ok = db.updateCustomerAddress(loggedInCustomer.getUsername(), address1, address2, town, postcode);
            // if the customer is updated correctly:
            if (ok)
            {
                // reflect in-memory object too
                loggedInCustomer.setAddressLine1(address1);
                loggedInCustomer.setAddressLine2(address2);
                loggedInCustomer.setTown(town);
                loggedInCustomer.setPostcode(postcode);

                JOptionPane.showMessageDialog(this, "Address updated successfully.", "Success",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            else
                
            {
                JOptionPane.showMessageDialog(this, "Could not update the address.",
                        "Update failed", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage(), "Validation", JOptionPane.WARNING_MESSAGE);
            
        } catch (Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        lblAddress2 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        lblTown = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblPostcode = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtTown = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtPostcode = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtFirstName.setEditable(false);

        lblAddress2.setText("Address 2:");

        btnModify.setText("MODIFY");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        lblTown.setText("Town:");

        btnBack.setText("BACK TO HOME");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPostcode.setText("Postcode:");

        lblMessage.setText("Welcome to our shop!");

        txtLastName.setEditable(false);

        lblFirstName.setText("Name:");

        lblLastName.setText("Surname:");

        lblAddress1.setText("Address 1:");

        lblTitle.setText("MODIFY YOUR ADDRESS :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModify)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTown, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTown)
                    .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPostcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(lblMessage)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify)
                    .addComponent(btnBack))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        
        String address1 = txtAddress1.getText();
        String address2 = txtAddress2.getText();
        String town = txtTown.getText();
        String postcode =txtPostcode.getText();


        DBManager db = new DBManager();
        boolean success = db.updateCustomerAddress(loggedInCustomer.getUsername(),address1, address2, town, postcode);

        if (success)
        {
            //lblMessage.setText("Address updated successfully!");
            // better option, allow have the info before going to Customer Home page
            JOptionPane.showMessageDialog(this, "Address updated successfully.");
            
            // Update in-memory object
            loggedInCustomer.setAddressLine1(address1);
            loggedInCustomer.setAddressLine2(address2);
            loggedInCustomer.setTown(town);
            loggedInCustomer.setPostcode(postcode);
            
            // Reload fresh data from DB (fixes your bug)
            //Customer refreshed = db.getCustomer(loggedInCustomer.getUsername());
            
            // Go back to CustomerHome with updated customer
            // this avoid the error of keeping the old address even thogh the db is been updated correctly
            new CustomerHome(loggedInCustomer).setVisible(true);
            dispose();
            
        } else
        {
            lblMessage.setText("Error updating the address");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new CustomerHome(loggedInCustomer).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//     //   java.awt.EventQueue.invokeLater(() -> new ChangeAddress().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPostcode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTown;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtTown;
    // End of variables declaration//GEN-END:variables
}
