/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// Package and Imports
package views; // Organise the class inside the 'views' package

import java.awt.BorderLayout;
import models.Customer; // Import Customer model for Login validation
import models.DBManager; // Import DBManager for db operations
import utils.EcoPalette;
import utils.ThemeManager;

import views.base.BaseFrame;// to add a logo
import views.common.HeaderBar;
//import javax.swing.*;  // Import swing methods (Edith : it is no necessary)
//import java.util.logging.Logger;

/**
 *The CustomerLogin class is part of a Java Swing application 
 * that provides a graphical interface for customers to log in. 
 * It allows users to enter their username and password, validates the input,
 * checks credentials against a database,
 * and navigates to the CustomerHome screen if authentication succeeds. 
 * It also includes navigation back to the main menu.
 * 
 * Key Concepts
 * 
 * Swing GUI Framework: Used for building desktop applications in Java.
 * JFrame: A top-level container that represents a window.
 * Event Handling: Uses ActionListener to respond to button clicks.
 * MVC Pattern: Separates views (CustomerLogin) from models (Customer, DBManager).
 * Validation: Ensures username and password are not empty before checking credentials.
 * Navigation: Switches between frames (CustomerLogin → CustomerHome or MainMenu).
 * Thread Safety: GUI updates run on the Event Dispatch Thread using invokeLater().
 * Logging: Uses Logger for error handling and debugging.
 * 
 * @author 30246196
 */

/*
CustomerLogin class creates a login window for customers.
It allows users to enter username and password, validates them,
and navigates to CustomerHomer if successful.
*/

public class CustomerLogin extends BaseFrame {
//public class CustomerLogin extends javax.swing.JFrame {
    
    // 1. Static Constants
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerLogin.class.getName());

    // 2. Attributes
    
    // 3. Constructor
    
    /** CustomerLogin Default Constructor()
     * Creates new form CustomerLogin and initialises components
     */
    public CustomerLogin() {
        initComponents();
        
        applyCommonTheme(); // fonts & component theme (ThemeManager + BaseFrame)
        applyColors();         //TODO eco palette
        installHeaderBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnReturnToMainMenu = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerLogin.setText("CUSTOMER LOGIN");

        lblUsername.setText("Username: ");

        lblPassword.setText("Password: ");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnReturnToMainMenu.setText("RETURN TO MAIN MENU");
        btnReturnToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToMainMenuActionPerformed(evt);
            }
        });

        pnlHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_128x128_no_orange.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustomerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnLogin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegister)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReturnToMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblCustomerLogin))
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnReturnToMainMenu)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 4. Getters and Setters(Not needed here because GUI builder handles components)
    
    // 5. Public Methods (Event Handlers)
    
    /* a) btnLoginACtionPerformed()
          Handles login button click.
        Validates input, check credentials in DB, and navigates to CustomerHome.
    */
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // When customer logs in correctly they should be taken to a new form
        // called Customer Home
        
        // Declares and retrieves the username and password from text fields
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        // Edith's improvement to check that they are not empty
        // Validates input
        if (username.isEmpty() || password.isEmpty()) 
        {
            lblErrorMessage.setText("Please enter both username and password.");
            return;
        }

        //Attempt to authentificate the customer via a DBManager class.
        DBManager db = new DBManager();// fix imports
        Customer loggedInCustomer =db.CustomerLogin(username, password);
        
        // If Login sucessful, open CustomerHome and pass logged-in customer
        if (loggedInCustomer != null)
        {   // changed in stage 8 
            //CustomerHome cHome = new CustomerHome();
            CustomerHome cHome = new CustomerHome(loggedInCustomer);// changed in stage 8
            cHome.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            lblErrorMessage.setText("Error: Incorrect Username/ Password");
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    // b) btnReturnToMainMenu Event Handle Method
    /*
     * Handles return button click.
     * Navigates back to MainMenu.
    */
    
    private void btnReturnToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToMainMenuActionPerformed
        // FROM Customer Login Frame to Main Menu Frame
        MainMenu mMainMenu = new MainMenu();
        // get visible the new form
        mMainMenu.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnToMainMenuActionPerformed

    // c) btnRegister
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        new RegisterForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    // d)Add the shared HeaderBar (logo + title) 
    private void installHeaderBar() {
        pnlHeader.setLayout(new BorderLayout());//fix imports
        HeaderBar header = new HeaderBar("Customer Login"); // logo handled inside HeaderBar
        pnlHeader.add(header, BorderLayout.CENTER);
    }

    /**
     * @param args the command line arguments
     */
    
    
    @Override
    protected void applyCommonTheme() {
        super.applyCommonTheme();
        ThemeManager.styleHeading(lblCustomerLogin);//fix imports

        // Call ThemeManager first (fonts/shapes), then enforce exact palette below
        ThemeManager.stylePrimary(btnLogin);
        ThemeManager.styleSecondary(btnRegister);
        ThemeManager.styleSecondary(btnReturnToMainMenu);
    }

    
/** Apply EcoPalette colors + sizes for CustomerLogin. */
private void applyColors() {
    // --- Background ---
    getContentPane().setBackground(EcoPalette.DUCK_EGG);

    // --- Heading ---
    lblCustomerLogin.setForeground(EcoPalette.STONE_GRAY);
    lblCustomerLogin.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 20));

    // --- Buttons: consistent sizing ---
    java.awt.Dimension primary = new java.awt.Dimension(160, 36);
    java.awt.Dimension wide    = new java.awt.Dimension(200, 36);
    btnLogin.setPreferredSize(primary);
    btnRegister.setPreferredSize(primary);
    btnReturnToMainMenu.setPreferredSize(wide);

    // --- Button colors ---
    // Darker green for primary action
    stylePrimaryButton(btnLogin);            // Leaf Green + white text
    // Softer green for secondary actions
    styleSecondaryButton(btnRegister);       // Eco Green + black text
    styleSecondaryButton(btnReturnToMainMenu);

    // --- Error label ---
    lblErrorMessage.setForeground(new java.awt.Color(180, 0, 0));
    lblErrorMessage.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12));
}
    
/** Darker green (Leaf) for primary buttons. */
private void stylePrimaryButton(javax.swing.JButton b) {
    b.setBackground(EcoPalette.LEAF_GREEN);
    b.setForeground(java.awt.Color.WHITE);
    b.setFocusPainted(false);
    b.setOpaque(true);
    b.setBorderPainted(false);
}

/** Softer green (Eco) for secondary buttons. */
private void styleSecondaryButton(javax.swing.JButton b) {
    b.setBackground(EcoPalette.ECO_GREEN);
    b.setForeground(java.awt.Color.BLACK);
    b.setFocusPainted(false);
    b.setOpaque(true);
    b.setBorderPainted(false);
}

    
    // 6. Main Method
    
    /**
     * @param args
     */
    
    // * Entry point: Sets look and feel and launches CustomerLogin window.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerLogin().setVisible(true));
    }

    // 7. Instance Attributes (GUI components declared here)
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReturnToMainMenu;
    private javax.swing.JLabel lblCustomerLogin;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel pnlHeader;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
