/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// Package and Imports
package views; // Organise the class inside the 'views' package

import models.Customer; // Import Customer model for Login validation
import models.DBManager; // Import DBManager for db operations
//import javax.swing.*;  // Import swing methods (Edith : it is no necessary)
//import java.util.logging.Logger;

/**
 *The CustomerLogin class is part of a Java Swing application 
 * that provides a graphical interface for customers to log in. 
 * It allows users to enter their username and password, validates the input,
 * checks credentials against a database,
 * and navigates to the CustomerHome screen if authentication succeeds. 
 * It also includes navigation back to the main menu.
 * 
 * Key Concepts
 * 
 * Swing GUI Framework: Used for building desktop applications in Java.
 * JFrame: A top-level container that represents a window.
 * Event Handling: Uses ActionListener to respond to button clicks.
 * MVC Pattern: Separates views (CustomerLogin) from models (Customer, DBManager).
 * Validation: Ensures username and password are not empty before checking credentials.
 * Navigation: Switches between frames (CustomerLogin → CustomerHome or MainMenu).
 * Thread Safety: GUI updates run on the Event Dispatch Thread using invokeLater().
 * Logging: Uses Logger for error handling and debugging.
 * 
 * @author 30246196
 */

/*
CustomerLogin class creates a login window for customers.
It allows users to enter username and password, validates them,
and navigates to CustomerHomer if successful.
*/

public class CustomerLogin extends javax.swing.JFrame {
    
    // 1. Static Constants
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerLogin.class.getName());

    // 2. Attributes
    
    // 3. Constructor
    
    /** CustomerLogin Default Constructor()
     * Creates new form CustomerLogin and initialises components
     */
    public CustomerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnReturnToMainMenu = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerLogin.setText("CUSTOMER LOGIN");

        lblUsername.setText("Username: ");

        lblPassword.setText("Password: ");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setText("REGISTER");

        btnReturnToMainMenu.setText("RETURN TO MAIN MENU");
        btnReturnToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtPassword))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReturnToMainMenu)
                            .addComponent(lblCustomerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblCustomerLogin)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnReturnToMainMenu)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 4. Getters and Setters(Not needed here because GUI builder handles components)
    
    // 5. Public Methods (Event Handlers)
    
    /* a) btnLoginACtionPerformed()
          Handles login button click.
        Validates input, check credentials in DB, and navigates to CustomerHome.
    */
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // When customer logs in correctly they should be taken to a new form
        // called Customer Home
        
        // Declares and retrieves the username and password from text fields
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        
        // Edith's improvement to check that they are not empty
        // Validates input
        if (username.isEmpty() || password.isEmpty()) 
        {
            lblErrorMessage.setText("Please enter both username and password.");
            return;
        }

        //Attempt to authentificate the customer via a DBManager class.
        DBManager db = new DBManager();// fix imports
        Customer loggedInCustomer =db.CustomerLogin(username, password);
        
        // If Login sucessful, open CustomerHome and pass logged-in customer
        if (loggedInCustomer != null)
        {   // changed in stage 8 
            //CustomerHome cHome = new CustomerHome();
            CustomerHome cHome = new CustomerHome(loggedInCustomer);// changed in stage 8
            cHome.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            lblErrorMessage.setText("Error: Incorrect Username/ Password");
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    // b) btnReturnToMainMenu Event Handle Method
    /*
     * Handles return button click.
     * Navigates back to MainMenu.
    */
    
    private void btnReturnToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToMainMenuActionPerformed
        // FROM Customer Login Frame to Main Menu Frame
        MainMenu mMainMenu = new MainMenu();
        // get visible the new form
        mMainMenu.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnToMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // 6. Main Method
    
    /**
     * @param args
     */
    
    // * Entry point: Sets look and feel and launches CustomerLogin window.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerLogin().setVisible(true));
    }

    // 7. Instance Attributes (GUI components declared here)
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReturnToMainMenu;
    private javax.swing.JLabel lblCustomerLogin;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
