/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.DBManager;
import models.Product;
import models.Staff;

/**
 *
 * @author 30246196
 */
public class EditProduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProduct.class.getName());

    // Declaration of currentOrder and loggedInCustomer
    private Product currentProduct;
    private Staff loggedInStaff;//fix imports
    
    /**
     * Creates new form EditProduct
     */
    public EditProduct(Staff s,Product p) 
    {
        loggedInStaff = s;
        currentProduct = p;
        
        initComponents();
        
        // check with a  customised welcome:
        lblStaff.setText("This is your basket, " + loggedInStaff.getFirstName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditProduct = new javax.swing.JLabel();
        lblStaff = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditProduct = new javax.swing.JTable();
        btnConfirmEditProduct = new javax.swing.JButton();
        btnBackToModifyByStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEditProduct.setText("EDIT PRODUCT");

        lblStaff.setText(" by Staff");

        tblEditProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ProductId", "ProductType", "ProductName", "Price", "StockLevel", "WattageOut", "EfficiencyRating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEditProduct);

        btnConfirmEditProduct.setText("CONFIRM EDITION");
        btnConfirmEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditProductActionPerformed(evt);
            }
        });

        btnBackToModifyByStaff.setText("BACK");
        btnBackToModifyByStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToModifyByStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnConfirmEditProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(btnBackToModifyByStaff)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditProduct)
                    .addComponent(lblStaff))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmEditProduct)
                    .addComponent(btnBackToModifyByStaff))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // . Events
    
    // a) btn ConfirmEditProduct
    
    private void btnConfirmEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditProductActionPerformed
        //edit a product from Products table in the db
        
        // Create a new DBManager instance to interact with the database.
        DBManager db = new DBManager(); // fix imports
        
        // TODO create modifyProduct(product)
        
        // TODO Show Confirmation frame/page
        
        // TODO Display confirmation modify frame
        
    }//GEN-LAST:event_btnConfirmEditProductActionPerformed

    private void btnBackToModifyByStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToModifyByStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToModifyByStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new EditProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToModifyByStaff;
    private javax.swing.JButton btnConfirmEditProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditProduct;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JTable tblEditProduct;
    // End of variables declaration//GEN-END:variables
}
