/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// 1. Package declaration

package views; // place the class inside the views package, 
// organise code into logical groups for better maintability

// 2. Imports

import utils.EcoPalette; // import the palette of colours from utils
import utils.ThemeManager;// import the theme to apply esier on the whole project
import views.base.BaseFrame;


/*
 * This is the MainMenu class for a Java Swing application.
 * It creates a simple GUI with buttons for 
 * Customer Login, Staff Login, and View Products.
 *
 *  Key concepts
 * 
 *  Swing GUI Framework: For building desktop applications.
 *  Inheritance: MainMenu extends JFrame.
 *  Event Handling: Using ActionListener.
 *  Layout Management: GroupLayout organizes components.
 *  Thread Safety: GUI updates on EDT.
 *  Navigation: Switching between frames.
 *  Logging: For error handling and debugging.
 *
 *  Background: Duck Egg (#E0F0E9) for calm eco feel.
 *  Title: Stone Gray (#6B7A6F) for contrast.
 *  Start (Primary): Leaf Green (#228B22) for strong emphasis.
 *  Settings (Secondary): Eco Green (#A8D5BA) for softer emphasis.
 *  Exit: Stone Gray for neutral tone.
 * 
 * eco‑themed background
 *
 * logo
 *
 * app name: GLASGOW GREEN RENEWABLES
 *
 * consistent spacing
 *
 * consistent styling
 *
 * @author 30246196
 */

public class MainMenu extends BaseFrame {
//public class MainMenu extends javax.swing.JFrame {
    
    // 3. Static Constants
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());
    
// 4. Instance Attributes (Fields)


// 5. Constructors
    
    // Constructor: Creates the MainMenu window and initialises components.
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        // set the title before calling applyCommonTheme()
        //setTitle("GLASGOW GREEN RENEWABLES");
        
        initComponents(); // Method that sets up the GUI elements
        
        applyCommonTheme(); // from BaseFrame
        applyThemeStyles();// centralize button/heading styles via ThemeManager
        
    }

    
// 8. Private Helper Methods
    
    /*
     * Initializes all GUI components (labels, buttons, layout).
     * This method is auto-generated by the GUI builder.
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainMenu = new javax.swing.JLabel();
        btnCustomerLogin = new javax.swing.JButton();
        btnStaffLogin = new javax.swing.JButton();
        btnViewProducts = new javax.swing.JButton();
        pnlHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblMainMenu.setText("MAIN MENU");

        btnCustomerLogin.setText("CUSTOMER LOGIN");
        btnCustomerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerLoginActionPerformed(evt);
            }
        });

        btnStaffLogin.setText("STAFF LOGIN");
        btnStaffLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffLoginActionPerformed(evt);
            }
        });

        btnViewProducts.setText("VIEW PRODUCTS");
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsActionPerformed(evt);
            }
        });

        pnlHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_128x128_no_orange.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaffLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerLogin)
                    .addComponent(btnViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCustomerLogin)
                .addGap(18, 18, 18)
                .addComponent(btnStaffLogin)
                .addGap(18, 18, 18)
                .addComponent(btnViewProducts)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 6. Getters and Setters (Optional for GUI, so skipping here)
    
    // 7. Public Methods (Event Handlers)
    
    // a) btnCustomerLogin Method Event Handler
    /*
        Handles Customer Login button click.
        Opens CustomerLogin window and hides MainMenu.
    */
    private void btnCustomerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginActionPerformed
        
        // Connects Main Menu with Customer Login Frame
        // name of the page CustomerLogin
        CustomerLogin cLogin = new CustomerLogin();
        // get visible the new form
        cLogin.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerLoginActionPerformed

    // b) btnStaffLogin Method Event Handler
    /*
        Handles Staff Login button click.
        Opens StaffLogin window and hides MainMenu.
    */
    
    private void btnStaffLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLoginActionPerformed
        
        // Connects Main Menu with Staff Login Frame
        // name of the page StaffLogin
        StaffLogin sLogin = new StaffLogin();
        // get visible the new form
        sLogin.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnStaffLoginActionPerformed

    
    // c) btnViewProducts Method Event Handler
    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed
        // TODO add your handling code here:
        // open a view with all the products by Heat Pump, Solar Panel and Replacement Part
        new ViewProductsForGuests().setVisible(true);
        // Cerrar la ventana actual (por ejemplo MainMenu)
        this.dispose();
    }//GEN-LAST:event_btnViewProductsActionPerformed

    // d) Applies styling method eco-friendly colours to the Main Menu UI
    
    /**
     * Applies Eco-friendly colours to the Main Menu UI.
     */
    
    // this will repeat and customised for each view
    protected void applyCommonTheme() {
            super.applyCommonTheme();
            //  style the heading & buttons with ThemeManager
        }

    
    private void applyThemeStyles() {
            // Heading
            ThemeManager.styleHeading(lblMainMenu);

            // Buttons
            ThemeManager.stylePrimary(btnViewProducts);   // primary CTA (Leaf Green)
            ThemeManager.styleSecondary(btnCustomerLogin); // soft Eco Green
            ThemeManager.styleSecondary(btnStaffLogin);    // soft Eco Green

            // Optional: ensure consistent sizing
            java.awt.Dimension btnSize = new java.awt.Dimension(160, 36);
            btnCustomerLogin.setPreferredSize(btnSize);
            btnStaffLogin.setPreferredSize(btnSize);
            btnViewProducts.setPreferredSize(btnSize);
        }

    /**
     * @param args the command line arguments
     */
    
    // 9. Main Method
    /*
        Main method: Starts the application.
    */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        
        // Apply global Eco tint once (before creating frames)
        ThemeManager.bootstrapLookAndFeel();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerLogin;
    private javax.swing.JButton btnStaffLogin;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
