/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// 1. Package declaration

package views; // place the class inside the views package, 
// organise code into logical groups for better maintability

// 2. Imports

//import javax.swing.*; 
//import java.util.logging.Logger;


/*
 * This is the MainMenu class for a Java Swing application.
 * It creates a simple GUI with buttons for 
 * Customer Login, Staff Login, and View Products.
 *
 *  Key concepts
 * 
 *  Swing GUI Framework: For building desktop applications.
 *  Inheritance: MainMenu extends JFrame.
 *  Event Handling: Using ActionListener.
 *  Layout Management: GroupLayout organizes components.
 *  Thread Safety: GUI updates on EDT.
 *  Navigation: Switching between frames.
 *  Logging: For error handling and debugging.
 * 
 * @author 30246196
 */

public class MainMenu extends javax.swing.JFrame {
    
    // 3. Static Constants
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());
    
// 4. Instance Attributes (Fields)
//    private JButton btnCustomerLogin;
//    private JButton btnStaffLogin;
//    private JButton btnViewProducts;
//    private JLabel jLabel1;

    // 5. Constructors
    
       // Constructor: Creates the MainMenu window and initialises components.
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents(); // Method that sets up the GUI elements
    }

    // 8. Private Helper Methods
    
    /*
     * Initializes all GUI components (labels, buttons, layout).
     * This method is auto-generated by the GUI builder.
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainMenu = new javax.swing.JLabel();
        btnCustomerLogin = new javax.swing.JButton();
        btnStaffLogin = new javax.swing.JButton();
        btnViewProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainMenu.setText("MAIN MENU");

        btnCustomerLogin.setText("CUSTOMER LOGIN");
        btnCustomerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerLoginActionPerformed(evt);
            }
        });

        btnStaffLogin.setText("STAFF LOGIN");
        btnStaffLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffLoginActionPerformed(evt);
            }
        });

        btnViewProducts.setText("VIEW PRODUCTS");
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblMainMenu)
                .addGap(47, 47, 47)
                .addComponent(btnCustomerLogin)
                .addGap(18, 18, 18)
                .addComponent(btnStaffLogin)
                .addGap(18, 18, 18)
                .addComponent(btnViewProducts)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 6. Getters and Setters (Optional for GUI, so skipping here)
    
    // 7. Public Methods (Event Handlers)
    
    // a) btnCustomerLogin Method Event Handler
    /*
        Handles Customer Login button click.
        Opens CustomerLogin window and hides MainMenu.
    */
    
    private void btnCustomerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginActionPerformed
        
        // Connects Main Menu with Customer Login Frame
        // name of the page CustomerLogin
        CustomerLogin cLogin = new CustomerLogin();
        // get visible the new form
        cLogin.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerLoginActionPerformed

    // b) btnStaffLogin Method Event Handler
    /*
        Handles Staff Login button click.
        Opens StaffLogin window and hides MainMenu.
    */
    
    private void btnStaffLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffLoginActionPerformed
        
        // Connects Main Menu with Staff Login Frame
        // name of the page StaffLogin
        StaffLogin sLogin = new StaffLogin();
        // get visible the new form
        sLogin.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnStaffLoginActionPerformed

    
    // c) btnViewProducts Method Event Handler
    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed
        // TODO add your handling code here:
        // open a view with all the products by Heat Pump, Solar Panel and Replacement Part
        new ViewProductsForGuests().setVisible(true);
        // Cerrar la ventana actual (por ejemplo MainMenu)
        this.dispose();
    }//GEN-LAST:event_btnViewProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // 9. Main Method
    /*
        Main method: Starts the application.
    */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerLogin;
    private javax.swing.JButton btnStaffLogin;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JLabel lblMainMenu;
    // End of variables declaration//GEN-END:variables
}
