/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;// from defining  ArrayList allProducts
import javax.swing.DefaultListModel;// from fix imports in categoryModel definition
import models.DBManager;// from fix imports
import models.Product;// from fix imports
import models.Staff;

/**
 *
 * @author 30246196
 */
public class ModifyProductForStaff extends javax.swing.JFrame {
    
    // 1. Static constants and Static variables
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModifyProductForStaff.class.getName());

    // add a global ArrayList variable to store the products
    private ArrayList<Product> allProducts;// fix imports create 'import models.Product; ' line above
    // added after stage 8 
    private Staff loggedInStaff;// the staff logged-in , fix imports
    
    // 2. Constructor
    
    /**
     * Creates new form EditProductForStaff
     */
    // constructor in the wiew layer for the GUI class
    //public ModifyProductForStaff() { //modify after stage 8 as Customer to pass the logged Staff
    public ModifyProductForStaff(Staff s)
    {
        // added after stage 8
        this.loggedInStaff = s;
        
        // add the connection to load the products
        DBManager db = new DBManager();//fix imports
        
        allProducts = db.loadProducts();// load products
        
        initComponents();
        
        // Customised the frame with the staff's name
        lblStaffInEditProduct.setText("by " + loggedInStaff.getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditProducts = new javax.swing.JLabel();
        btnReturnStaffHome = new javax.swing.JButton();
        lblCategories = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProductsByCategory = new javax.swing.JList<>();
        btnEditProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblHandlingError = new javax.swing.JLabel();
        lblStaffInEditProduct = new javax.swing.JLabel();
        lblConfirmation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEditProducts.setText("MODIFY PRODUCTS");

        btnReturnStaffHome.setText("RETURN TO STAFF HOME");
        btnReturnStaffHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnStaffHomeActionPerformed(evt);
            }
        });

        lblCategories.setText("CATEGORIES");

        lblProduct.setText("PRODUCT");

        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "HeatPump", "SolarPanel" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategories);

        jScrollPane2.setViewportView(lstProductsByCategory);

        btnEditProduct.setText("EDIT PRODUCT");
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("DELETE PRODUCT");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        lblStaffInEditProduct.setText("by Staff");

        lblConfirmation.setText("Confirmation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReturnStaffHome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStaffInEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHandlingError, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(85, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditProducts)
                    .addComponent(btnReturnStaffHome)
                    .addComponent(lblStaffInEditProduct))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategories)
                    .addComponent(lblProduct))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHandlingError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmation))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditProduct)
                    .addComponent(btnDeleteProduct))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // 3. Event Handlers
    
    // a)  Back/Return button
    // 
    // Navigates back to StaffHome
    private void btnReturnStaffHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnStaffHomeActionPerformed
        StaffHome sHome = new StaffHome(loggedInStaff);// added by ne in stage 6
        sHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnStaffHomeActionPerformed

    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        // from ValueChanged in Events in LstCategories:
        
        // define a String variable with the value selected in the Categories list
        String selectedCategory = lstCategories.getSelectedValue();
        
        // define a variable
        /*
        DefaultListModel:

        This is a class from the Swing library in Java.
        It is used to store a list of elements, typically for use with GUI components like JList.
        It provides methods to add, remove, and access elements in the list.
        
        categoryModel:

        This is the name of the variable being declared.
        It will hold the instance of DefaultListModel.
        
        new DefaultListModel():

        This creates a new, empty list model object.
        */
        DefaultListModel categoryModel = new DefaultListModel();// fix imports
        
        // see User or Staff class file
        for(Product p:allProducts)
        {
                                            //package.class name
            if(p.getClass().getName().equals("models." + selectedCategory))
            {
                categoryModel.addElement(p);// addd this element to the categoryModel list
                
            }
        }
        //Sets the model that represents the contents or "value" of the list, 
        //notifies property change listeners, and then clears the list's selection.
        lstProductsByCategory.setModel(categoryModel);
    }//GEN-LAST:event_lstCategoriesValueChanged

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        
        // error detection
        // select an product from 2nd list
        // unselected is -1

        // Check if a category is selected
        if (lstCategories.getSelectedIndex() == -1) 
        {
            lblHandlingError.setText("Please select a category first.");
            return;
        }

        // Check if is a product is selected
        if(lstProductsByCategory.getSelectedIndex() == -1)// no selected
        {
            lblHandlingError.setText("Please select a product from the list.");
            //return;
        }
        
    }//GEN-LAST:event_btnEditProductActionPerformed

    // Handler event method
    // stage 9
    
    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // check if a product is selected
       
        if (lstProductsByCategory.getSelectedIndex() !=-1)
        {
            Object selectedProductObject = (Object)lstCategories.getSelectedValue();
            Product selectedProduct= (Product)selectedProductObject;
            
            DBManager db = new DBManager();
            db.deleteProduct(selectedProduct.getProductId());// need getAnimal()
            
            // make the animal delete from the listbox
            DefaultListModel productsModel = (DefaultListModel)lstProductsByCategory.getModel();// check the meaning
            productsModel.remove(lstProductsByCategory.getSelectedIndex());// delete the animal from the list
            
            // refresh db
            allProducts = db.loadProducts();
            
            lblConfirmation.setText("Product Deleted Successfully");
        }
        else
        lblConfirmation.setText("Error: Select Product First");
        
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ModifyProductForStaff().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnReturnStaffHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblEditProducts;
    private javax.swing.JLabel lblHandlingError;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblStaffInEditProduct;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<String> lstProductsByCategory;
    // End of variables declaration//GEN-END:variables
}
