/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import models.DBManager;
import models.Product;
import models.Staff;
import utils.ThemeManager;
import views.base.BaseFrame;

/**
 *
 * @author 30246196
 */
public class SearchSortProducts extends BaseFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchSortProducts.class.getName());

    private DefaultListModel<String> model = new DefaultListModel<>();
    
    // list of products load from the DB
    private ArrayList<Product> products = new ArrayList<>(); //fix imports  
    
    private Staff loggedInStaff;// the staff logged-in 
    /**
     * Creates new form SearchSortProducts
     */
    public SearchSortProducts(Staff s) {
        this.loggedInStaff = s;
        
        ThemeManager.styleBackButton(btnBack);// fix imports, apply same colour to Back Button
        initComponents();
        lstProducts.setModel(model);
        
        btnBinarySearch.setEnabled(false);// button not enabled
        
        loadProductsFromDB();
        displayProducts();
    }

    // Method loadProductsFromDB()
    private void loadProductsFromDB(){
        DBManager db = new DBManager();//fix imports
        products = db.loadProducts();
    }
           
    // Method displayProducts()
    private void displayProducts()
    {
        model.clear();
        for(Product p: products)
        {
            model.addElement(p.getProductName() + " - £" + p.getPrice());
        }
    }
    
    // Method BubbleSort()sorted in ascending order by price 
    private void bubbleSortProducts()
    {
        int n = products.size();
        boolean swapped;
        
        for (int i = 0; i < n - 1; i++)
        {
            swapped = false;
            
            for (int j = 0; j < n - i - 1; j++)
            {
                if (products.get(j).getPrice() > products.get(j + 1).getPrice())
                {
                    Product temp = products.get(j);
                    products.set(j, products.get(j + 1));
                    products.set(j + 1, temp);
                    swapped = true;
                }
            }
            if(!swapped)
                break;
        }
    }
    
    // Method Selection Sort Ascending
    private void selectionSortProducts() 
    {
        int n = products.size();

        for (int i = 0; i < n - 1; i++)
        {
            int minIndex = i;

            // Look for the lowest price
            for (int j = i + 1; j < n; j++)
            {
               if (products.get(j).getPrice() < products.get(minIndex).getPrice())
                {
                    minIndex = j;
                }
            }

        // Swap if we find a lower value
        if (minIndex != i)
            {
                Product temp = products.get(i);
                products.set(i, products.get(minIndex));
                products.set(minIndex, temp);
            }
        }
    }
    
    // Method Linear Search
    private void linearSearch(double targetPrice)
    { 
        model.clear();
        boolean found = false;
        
        for (Product p : products)
            { if (p.getPrice() == targetPrice)
                { model.addElement(p.getProductName() + " - £" + p.getPrice());
                found = true;
                }
            } if (!found)
                { 
                  model.addElement("No product found with price £" + targetPrice);
                }
    }
    
    // Method Binary Search
    private void binarySearch(double targetPrice)
    {
       model.clear();
       
       int left = 0;
       int right = products.size() - 1;
       
       while (left <= right)
       {
          int mid = (left + right) / 2;
          double midPrice = products.get(mid).getPrice();
          
          if (midPrice == targetPrice)
          {
              Product p = products.get(mid);
              model.addElement(p.getProductName() + " - £" + p.getPrice());
              return;
          }
          else if (midPrice < targetPrice)
          {
              left = mid + 1;
          }
          else
          {
              right = mid -1;
          }
       }
       model.addElement("No product found with price £" + targetPrice);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList<>();
        btnBubbleSort = new javax.swing.JButton();
        btnSelectionSort = new javax.swing.JButton();
        lblEnterProductPrice = new javax.swing.JLabel();
        txtSearchPrice = new javax.swing.JTextField();
        btnLinearSearch = new javax.swing.JButton();
        btnBinarySearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstProducts);

        btnBubbleSort.setText("Bubble Sort");
        btnBubbleSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleSortActionPerformed(evt);
            }
        });

        btnSelectionSort.setText("Selection Sort");
        btnSelectionSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectionSortActionPerformed(evt);
            }
        });

        lblEnterProductPrice.setText("Enter Product Price:");

        btnLinearSearch.setText("Linear Search");
        btnLinearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinearSearchActionPerformed(evt);
            }
        });

        btnBinarySearch.setText("Binary Search");
        btnBinarySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarySearchActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBubbleSort)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelectionSort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEnterProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(165, 165, 165)
                                .addComponent(btnLinearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBinarySearch)
                            .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBubbleSort)
                    .addComponent(btnSelectionSort)
                    .addComponent(lblEnterProductPrice)
                    .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLinearSearch)
                        .addComponent(btnBinarySearch))
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBubbleSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleSortActionPerformed
        bubbleSortProducts();
        displayProducts();
        btnBinarySearch.setEnabled(true); //now active
    }//GEN-LAST:event_btnBubbleSortActionPerformed

    private void btnSelectionSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectionSortActionPerformed
        selectionSortProducts();
        displayProducts();
        btnBinarySearch.setEnabled(true); // now active
    }//GEN-LAST:event_btnSelectionSortActionPerformed

    private void btnLinearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinearSearchActionPerformed
        try
        {
          double price = Double.parseDouble(txtSearchPrice.getText());
          linearSearch(price);
        }
        catch(NumberFormatException e)
            {
                model.clear();
                model.addElement("Invalid price entered.");
            }
    }//GEN-LAST:event_btnLinearSearchActionPerformed

    private void btnBinarySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarySearchActionPerformed
        try
        {
            double price = Double.parseDouble(txtSearchPrice.getText());
            binarySearch(price);
        }
        catch(NumberFormatException e)
        {
            model.clear();
            model.addElement("Invalid price entered.");
        }
                
    }//GEN-LAST:event_btnBinarySearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // button to Staff Home page
        new StaffHome(loggedInStaff).setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(() -> new SearchSortProducts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBinarySearch;
    private javax.swing.JButton btnBubbleSort;
    private javax.swing.JButton btnLinearSearch;
    private javax.swing.JButton btnSelectionSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterProductPrice;
    private javax.swing.JList<String> lstProducts;
    private javax.swing.JTextField txtSearchPrice;
    // End of variables declaration//GEN-END:variables
}
