/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.DefaultListModel;

import models.Customer;
import models.Order;
import utils.ThemeManager;

import views.base.BaseFrame;

/**
 *
 * @author 30246196
 */
public class SelectPaymentMethod extends BaseFrame {
    
    // 1. Static constants and Static variables
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectPaymentMethod.class.getName());

    
    // 2. Attributes
    private Order currentOrder;// represents the customer's current shopping basket--fix imports   
    private Customer loggedInCustomer;//the customer who is logged in
    
    DefaultListModel<Integer> model = new DefaultListModel<>(); //fix imports

    
    /**
     * Creates new form SelectPaymentMethod
     */
    public SelectPaymentMethod(Order o,Customer c)
    {
        this.currentOrder = o;
        this.loggedInCustomer = c;
        initComponents();
        lstCards.setModel(model);
        
        loadCardsIntoList(loggedInCustomer);
        
        applyCommonTheme(); // adds HeaderBar + background
        applyThemeStyles();// styles buttons, labels, etc.
    }

    // Theme Events
    
    /**
     * Applies Eco-friendly colours to the Main Menu UI.
     */
    
    // this will repeat and customised for each view
//    protected void applyCommonTheme() {
//            super.applyCommonTheme();
//            //  style the heading & buttons with ThemeManager
//        }

    
    private void applyThemeStyles() {
            // Heading
            ThemeManager.styleHeading(lblSelectedPaymentCard);

            // Buttons
            ThemeManager.styleSecondary(btnDeleteSelectedCard); // soft Eco Green
            ThemeManager.stylePrimary(btnAddNewCard); //primary CTA (Leaf Green) 
            ThemeManager.stylePrimary(btnAddNewDefaultCard); // primary CTA (Leaf Green)
            ThemeManager.stylePrimary(btnConfirmPaymentMethod); // primary CTA (Leaf Green)

//            // Optional: ensure consistent sizing
//            java.awt.Dimension btnSize = new java.awt.Dimension(160, 36);
//            btnCustomerLogin.setPreferredSize(btnSize);
//            btnStaffLogin.setPreferredSize(btnSize);
//            btnViewProducts.setPreferredSize(btnSize);
        }
    
    // Methods
    
    public void loadCardsIntoList(Customer c)
    { 
        model.clear();
        for (int card : c.getCardNumbers())
        { 
            model.addElement(card);
        } 
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectedPaymentCard = new javax.swing.JLabel();
        lblEnterNewCard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCards = new javax.swing.JList<>();
        btnConfirmPaymentMethod = new javax.swing.JButton();
        btnAddNewCard = new javax.swing.JButton();
        btnAddNewDefaultCard = new javax.swing.JButton();
        btnDeleteSelectedCard = new javax.swing.JButton();
        txtEnterNewCard = new javax.swing.JTextField();
        txtAddNewDefaultCard = new javax.swing.JTextField();
        lblAddNewDefaultCard = new javax.swing.JLabel();
        lblConfirmation = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSelectedPaymentCard.setText("Select Payment Card:");

        lblEnterNewCard.setText("Enter New Card No:");

        jScrollPane1.setViewportView(lstCards);

        btnConfirmPaymentMethod.setText("Confirm Payment Method");
        btnConfirmPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmPaymentMethodActionPerformed(evt);
            }
        });

        btnAddNewCard.setText("Add");
        btnAddNewCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCardActionPerformed(evt);
            }
        });

        btnAddNewDefaultCard.setText("Add");
        btnAddNewDefaultCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDefaultCardActionPerformed(evt);
            }
        });

        btnDeleteSelectedCard.setText("Delete Selected Card");
        btnDeleteSelectedCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSelectedCardActionPerformed(evt);
            }
        });

        lblAddNewDefaultCard.setText("Add New Default Card:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirmPaymentMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(lblSelectedPaymentCard, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddNewCard)
                            .addComponent(btnAddNewDefaultCard)
                            .addComponent(btnDeleteSelectedCard)
                            .addComponent(lblAddNewDefaultCard, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnterNewCard, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnterNewCard)
                            .addComponent(txtAddNewDefaultCard, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnterNewCard)
                            .addComponent(lblSelectedPaymentCard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnterNewCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnAddNewCard)
                        .addGap(18, 18, 18)
                        .addComponent(lblAddNewDefaultCard)
                        .addGap(1, 1, 1)
                        .addComponent(txtAddNewDefaultCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddNewDefaultCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteSelectedCard)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmPaymentMethod)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCardActionPerformed
        int cardNumber = Integer.parseInt(txtEnterNewCard.getText());
        //add the card to the customer
        loggedInCustomer.addCard(cardNumber);
        //refresh the list
        loadCardsIntoList(loggedInCustomer);
        //clean the textbox
        txtEnterNewCard.setText("");
        
    }//GEN-LAST:event_btnAddNewCardActionPerformed

    private void btnAddNewDefaultCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDefaultCardActionPerformed
        int cardNumber = Integer.parseInt(txtAddNewDefaultCard.getText());
        // add the card at the begining of the LinkedList of customer
        loggedInCustomer.addFirstCard(cardNumber);
        //refresh the listbox
        loadCardsIntoList(loggedInCustomer);
        // clean the textbox
        txtAddNewDefaultCard.setText("");
        
    }//GEN-LAST:event_btnAddNewDefaultCardActionPerformed

    private void btnDeleteSelectedCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelectedCardActionPerformed
        int selectedIndex = lstCards.getSelectedIndex();
        
        if (selectedIndex == -1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a card to delete.");
            return;
        }
        
        // Delete card from the LinkedList of customer
        loggedInCustomer.removeCard(selectedIndex);
        
        // Refresh the listbox
        loadCardsIntoList(loggedInCustomer);
        
    }//GEN-LAST:event_btnDeleteSelectedCardActionPerformed

    private void btnConfirmPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmPaymentMethodActionPerformed
        // Check if a card is selected to pay
        if (lstCards.getSelectedIndex() == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a card.");
            return;
        }else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Thanks for shopping with us, your payment was succesful!");
            // pass the logged customer back to CustomerHome page  changed in stage 8
        CustomerHome home = new CustomerHome(loggedInCustomer);//TODO CHECK
        home.setVisible(true);
        this.setVisible(false);
        }   
        
    }//GEN-LAST:event_btnConfirmPaymentMethodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new SelectPaymentMethod().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCard;
    private javax.swing.JButton btnAddNewDefaultCard;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmPaymentMethod;
    private javax.swing.JButton btnDeleteSelectedCard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddNewDefaultCard;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblEnterNewCard;
    private javax.swing.JLabel lblSelectedPaymentCard;
    private javax.swing.JList<Integer> lstCards;
    private javax.swing.JTextField txtAddNewDefaultCard;
    private javax.swing.JTextField txtEnterNewCard;
    // End of variables declaration//GEN-END:variables
}
