/*
 in the shop.

*/

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package views;// the class is in views package, part of an MVC architecture(Model-View-Controller)
/*Swing uses the Model-View-Controller (MVC) pattern internally, where:
    Model = The data and logic (what the component displays).
    View = The visual representation (how it looks).
    Controller = Handles user interaction (events).
*/
import static java.lang.Integer.parseInt;// statically imported to convert String to integer
import java.util.ArrayList;//
import javax.swing.DefaultListModel;// Swing component
import models.Customer;// model class Customer
import models.DBManager;// model class BDManager
import models.Order;// model class Order
import models.OrderLine;// model class OrderLine
import models.Product;// model class Product
import utils.ThemeManager;
import views.base.BaseFrame;

/**
 * ShopPageForCustomers is a Swing-based GUI class
 * that represents a shopping page for customers
 * 
 * Key Concepts
 * 
 * 
 * @author 30246196
 */
// this UI(User Interface) class extends JFrame, it is a GUI window, and 
// contains Swing components:JButton(btnAddToBasket),JList(lstCategories,lstProductsByCategory)
// JTextField(txtQuantity)and JLabel(lblConfirmation, lblWelcomeBasket)
public class ShopPageForCustomers extends BaseFrame {
    
    // 1. Static constants and Static variables
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopPageForCustomers.class.getName());
    
    // 2. Attributes
    
    // declaration added stage 8
    // TODO check if these variables can be Final variables
    private ArrayList<Product> allProducts ;// stores all products loaded from the db   
    private Order currentOrder;// represents the customer's current shopping basket--fix imports   
    private Customer loggedInCustomer;//the customer who is logged in
    
    
    // 3. Constructor
    
    // constructor in the wiew layer for the GUI class
    //public ShopPageForCustomers() { //modify in stage 8 to add Customer and Order
    public ShopPageForCustomers(Customer c,Order o) 
    {
        // added       
        //currentOrder = new Order();// empty order
        this.currentOrder = o;// added this.
        this.loggedInCustomer = c;// added
                
        //load the products from the db using DBManager
        DBManager db  = new DBManager();       
        allProducts = db.loadProducts();
        
        initComponents();// initialises the view IU components (autogenerated by NetBeans GUI builder)
        
        ThemeManager.styleBackButton(btnBack);// fix imports, apply same colour to Back Button
        
        // Personalise the basket with customer 's name:
        lblWelcomeBasket.setText("These are our products, " + loggedInCustomer.getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnViewBasket = new javax.swing.JButton();
        btnAddToBasket = new javax.swing.JButton();
        lblProducts = new javax.swing.JLabel();
        lblCategories = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProductsByCategory = new javax.swing.JList<>();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblConfirmation = new javax.swing.JLabel();
        lblWelcomeBasket = new javax.swing.JLabel();
        lblPartFor = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPartFor = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewBasket.setText("VIEW BASKET");
        btnViewBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBasketActionPerformed(evt);
            }
        });

        btnAddToBasket.setText("ADD TO BASKET");
        btnAddToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBasketActionPerformed(evt);
            }
        });

        lblProducts.setText("PRODUCTS");

        lblCategories.setText("CATEGORIES");

        lblProduct.setText("PRODUCT");

        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "HeatPump", "SolarPanel", "ReplacementPart" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategories);

        jScrollPane2.setViewportView(lstProductsByCategory);

        lblQuantity.setText("Quantity: ");

        lblWelcomeBasket.setText("Shop Welcome");

        lblPartFor.setText("REPLACEMENT FOR");
        lblPartFor.setEnabled(false);

        lstPartFor.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SolarPanel", "HeatPump", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPartFor.setEnabled(false);
        lstPartFor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPartForValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstPartFor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategories)
                        .addGap(158, 158, 158)
                        .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWelcomeBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(lblProducts)
                                .addGap(121, 121, 121)
                                .addComponent(btnViewBasket)
                                .addContainerGap(66, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddToBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPartFor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblWelcomeBasket)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProducts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategories)
                            .addComponent(lblProduct)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnViewBasket)
                        .addGap(56, 56, 56)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblPartFor)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addGap(2, 2, 2)
                .addComponent(lblConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAddToBasket)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 4. Event handlers
    
    // a) Category Selection
    /*
    When a category is selected, it filters products by category and updates the second list (lstProductsByCategory).
    */
    //method triggered by ListSelectionEvent whenever the user selects a different category in the lstCategories list
    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        // 
        String selectedCategory = lstCategories.getSelectedValue();//retrieve the selected category
        
        // creates an empty model to hold products filtered by category
        DefaultListModel categoryModel = new DefaultListModel();// create a new DefaultListModel to hold products of that category --fix imports
        
        // see User or Customer class file
        // loops through allProducts and 
        for(Product p: allProducts)
        {
            //checks if each product belongs to the selected category ("Solar Panel" or "Heat Pump" or "ReplacementPart")
                                            //package.class name
            if (p.getClass().getName().equals("models." + selectedCategory))//
            {
                categoryModel.addElement(p);//add the product p to the model
            }
        }
        
        lstProductsByCategory.setModel(categoryModel);// updates the second list (lstProductsByCategory)
        
    }//GEN-LAST:event_lstCategoriesValueChanged

    // b) Back Button
    
    // Navigates back to the CustomerHome
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      
        // return to CustomerHome frame
        CustomerHome cHome = new CustomerHome(loggedInCustomer);//changed stage 8
        cHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    // c) Add to Basket
    /*
    Reads quantity from txtQuantity.
    Checks if a product is selected and if enough stock is available.
    Creates an OrderLine and adds it to the current order.
    */
    private void btnAddToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBasketActionPerformed
        
        // error detection
        // select an product from 2nd list
        // unselected is -1
        
        // Check if a category is selected
        if (lstCategories.getSelectedIndex() == -1) 
        {
            lblConfirmation.setText("Please select a category first.");
            return;
        }

        // Check if is a product is selected
        if(lstProductsByCategory.getSelectedIndex() == -1)// no selected
        {
            lblConfirmation.setText("Please select a product from the list.");
            return;
        }
        
        // TODO DONE invalid quantity input (negative, 0, non integer numbers, non numbers) handling error
        
        // create and initialise variable quantity from the textbox
        String textquantity = txtQuantity.getText();
        
     
        // Check if quantity field is empty
        // isEmpty() can only be called on a String object, quantity is int
        if (textquantity.isEmpty())// or textquantity.isEmpty()
        {
            lblConfirmation.setText("Please enter a quantity");
            return; //stop further execution
        }        
        
        int q;
        
        try{
            q = parseInt(textquantity);
            if(q<=0)
            {
                lblConfirmation.setText("Quantity must be a positive number.");
                return;
            }
        }catch (NumberFormatException e)
            {
                lblConfirmation.setText("Invalid quantity. Please enter a whole number.");
                return;
            }
               
        
        
        // get the product which is selected
        // convert into an Product
            
        // getSelectedValue() returns a String, it cannot convert directly into String
        //change to: top level Object that includes a String
        Object selectedProductObject = (Object)lstProductsByCategory.getSelectedValue();                        
        Product selectedProduct =(Product)selectedProductObject;
            
        int stock = selectedProduct.getStockLevel();
            
        // Check stock availability, now that I got the Product 
            if (stock>=q) //  TODO check
            {
                // create OrderLine with that product
                OrderLine ol = new OrderLine(selectedProduct,q);// ctrl + space bar to get the parameters
                
                // create an getter for orderlineId
                // DO NOT COPY THIS LINE
                //currentOrder.getOrderLines().put (ol.getOrderLineId() ,ol);
                
                currentOrder.addOrderLine(ol);
                lblConfirmation.setText("Product Added to Basket");
            }
            else
            {
                lblConfirmation.setText("Only " + stock + " units available.Please, reduce quantity.");
            }
    }//GEN-LAST:event_btnAddToBasketActionPerformed

    // d) View Basket
    /*
    Opens the Basket page with the current order and the loggedin customer
    */
    private void btnViewBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBasketActionPerformed
        
        Basket b = new Basket(loggedInCustomer,currentOrder);//modified
        b.setVisible(true);
        this.setVisible(false);
        // added in stage 8
        // pass the logged in customer and the current order
        
         //check with a  customised welcome:
        lblWelcomeBasket.setText("This is your basket, " + loggedInCustomer.getFirstName());
        
    }//GEN-LAST:event_btnViewBasketActionPerformed

    // e) partFor selection (Replacement Part for SolarPanel or for Heat Pump) added in stage 8 extra
    private void lstPartForValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPartForValueChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lstPartForValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
// comment in stage 8
//        java.awt.EventQueue.invokeLater(() -> new ShopPageForCustomers().setVisible(true));
    }

    // GUI Components
    /*
    Declares Swing components like buttons, labels, lists, and text fields.
    These are managed by initComponents() (NetBeans auto-generated).
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBasket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewBasket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblPartFor;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblWelcomeBasket;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<String> lstPartFor;
    private javax.swing.JList<String> lstProductsByCategory;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
