/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.Staff;

/**
 *
 * @author 30246196
 */
public class StaffHome extends javax.swing.JFrame {
    
    // 1. Static variables
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffHome.class.getName());

    /**
     * Creates new form StaffHome
     */
    // Edith added : Modify StaffHome to accept a Staff object in its constructor.
    // declaration of loggedInStaff as Staff object
    private final Staff loggedInStaff;// fix imports added after stage 8 , changed to final
    
    // 2. Constructor
    
    public StaffHome(Staff staff) // added the parameter after stage 8
    { 
        this.loggedInStaff = staff;// added after stage 8    
        initComponents();
        
        // Show customised welcome for staff:
        lblWelcomeStaff.setText("Welcome to work " + loggedInStaff.getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeStaff = new javax.swing.JLabel();
        btnModifyProducts = new javax.swing.JButton();
        btnSearchSortProducts = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnModifyOrders1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcomeStaff.setText("Welcome to work!");

        btnModifyProducts.setText("MODIFY PRODUCTS");
        btnModifyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyProductsActionPerformed(evt);
            }
        });

        btnSearchSortProducts.setText("SEARCH AND SORT PRODUCTS");
        btnSearchSortProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSortProductsActionPerformed(evt);
            }
        });

        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnModifyOrders1.setText("VIEW ALL ORDERS");
        btnModifyOrders1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyOrders1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblWelcomeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchSortProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnModifyOrders1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblWelcomeStaff)
                .addGap(53, 53, 53)
                .addComponent(btnModifyProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSearchSortProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnModifyOrders1)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 3. Event Handling Methods
    
    // a) btnLOgOut Event Method
    
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // From Staff Login Frame to Main Menu Frame
        MainMenu mMainMenu = new MainMenu();
        // get visible the new form
        mMainMenu.setVisible(true);
        // hide the current form
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    // b) btnModifyProducts Event Method
    
    private void btnModifyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyProductsActionPerformed
        // from Staff Login Frame to ModifyProductForStaff frame, 'EDIT PRODUCTS' button
        ModifyProductForStaff sEditProductForStaff = new ModifyProductForStaff(loggedInStaff);
        //get visible the new frame
        sEditProductForStaff.setVisible(true);
        // hide the current frame
        this.setVisible(false);
        
    }//GEN-LAST:event_btnModifyProductsActionPerformed

    private void btnSearchSortProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSortProductsActionPerformed
        // ADDED IN STAGE 12 
        SearchSortProducts ssp = new SearchSortProducts();
        ssp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSearchSortProductsActionPerformed

    private void btnModifyOrders1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyOrders1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyOrders1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // 4. Main 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new StaffHome().setVisible(true));
    }

    // 5. Declaration of Variables
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModifyOrders1;
    private javax.swing.JButton btnModifyProducts;
    private javax.swing.JButton btnSearchSortProducts;
    private javax.swing.JLabel lblWelcomeStaff;
    // End of variables declaration//GEN-END:variables
}
