/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

import models.DBManager;
import models.HeatPump;
import models.Product;
import models.ReplacementPart;
import models.SolarPanel;

import utils.EcoPalette;
import utils.ThemeManager;

import views.base.BaseFrame;
import views.common.HeaderBar;

/**
 *
 *  ViewProductsForGuests
 * Displays product categories and product list for non‑logged‑in users.
 * 
 * @author 30246196
 */
public class ViewProductsForGuests extends BaseFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewProductsForGuests.class.getName());

    //1. Attributes
    
    // array to save all the products of the db Shop
    private ArrayList<Product> allProducts;// fix imports
    
    /**
     * Creates new form ViewProductsForGuests
     */
    public ViewProductsForGuests() {
        super();
        
        DBManager db = new DBManager();// fix imports
        allProducts = db.loadProducts();
        
        initComponents();
        
        ThemeManager.styleBackButton(btnBack);// fix imports, apply same colour to Back Button
        
        applyCommonTheme(); // Header + Footer + Background
        applyViewTheme();   // this view's specifics (labels, lists, back button)
        applyThemeStyles(); // styles buttons, labels, etc.
        
//        HeaderBar header = new HeaderBar("Products for Guests");//fix imports
//        pnlHeader.setLayout(new BorderLayout());
//        pnlHeader.add(header, BorderLayout.CENTER);


    }
    
    // Theme Methods
    
    @Override protected void applyCommonTheme()
    {
        super.applyCommonTheme();
        ThemeManager.styleHeading(lblWelcome);
        ThemeManager.styleHeading(lblCategories);
        ThemeManager.styleHeading(lblProducts);
    }
    
    private void applyThemeStyles()
    {
        ThemeManager.stylePrimary(btnBack);
    }
    
    private void applyViewTheme()
    {
        lblInformation.setForeground(EcoPalette.TEXT_MUTED);
        
        ThemeManager.styleList(lstCategories, jScrollPane3);
        ThemeManager.styleList(lstProducts, jScrollPane2);
        
        lblWelcome.setFont(lblWelcome.getFont().deriveFont( Font.BOLD, lblWelcome.getFont().getSize2D() + 1f));
    }
    
    // Method loadProducts
    
    // this method is used just ViewProductsForGuests and
    //shows the name of the product and the price
    
    private void loadProducts(String category)
    { 
        DefaultListModel<String> model = new DefaultListModel<>();//fix imports
        
        for (Product p : allProducts)
        { 
            switch (category)
            { 
                case "Heat Pump": if (p instanceof HeatPump)
                    { 
                        model.addElement(p.getProductName() + " - £" + p.getPrice());
                    } 
                    break;
                    case "Solar Panel":
                        if (p instanceof SolarPanel)
                        {
                            model.addElement(p.getProductName() + " - £" + p.getPrice());
                        }
                        break;
                    case "Replacement Part":
                        if (p instanceof ReplacementPart)
                        {
                            model.addElement(p.getProductName() + " - £" + p.getPrice());
                        }
                        break;
            }
        }
        lstProducts.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCategories = new javax.swing.JLabel();
        lblProducts = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        lblInformation = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblWelcome.setText("WELCOME!");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCategories.setText("Categories");

        lblProducts.setText("Products");

        jScrollPane2.setViewportView(lstProducts);

        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Heat Pump", "Solar Panel", "Replacement Part" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCategories);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(lblProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBack))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWelcome)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategories)
                    .addComponent(lblProducts))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        if (!evt.getValueIsAdjusting()) {
        
            String selected = lstCategories.getSelectedValue();
            
            if (selected != null) {
                // call the method to load the products
                loadProducts(selected);   //loadProducts local method             
            }
        }
    }//GEN-LAST:event_lstCategoriesValueChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewProductsForGuests().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblInformation;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<String> lstProducts;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
