/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import models.Customer;
import models.DBManager;
import models.Order;

/**
 *
 * @author 30246196
 */
public class ViewOrders extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewOrders.class.getName());

    private Customer loggedInCustomer;
    private DefaultListModel<String> model = new DefaultListModel<>();
    /**
     * Creates new form ViewOrders
     */
    public ViewOrders(Customer c) {
        this.loggedInCustomer = c;
        initComponents();
        
        lblTitle.setText("Your orders " + loggedInCustomer.getFirstName() + ": reference, date and total" );
        lstOrders.setModel(model);
        loadOrdersForCustomer();
    }

    // Load only orders that belong to the logged-in customer
    private void loadOrdersForCustomer()
    {
       model.clear();
       
       // validate customer
       String customerUsername =(loggedInCustomer != null)? loggedInCustomer.getUsername() : null;
       if (customerUsername == null || customerUsername.trim().isEmpty() )
       {
           model.addElement("No customer is logged in.");
           return;
       }
       
       // load orders from this customer from DB
       DBManager db = new DBManager();
       //ArrayList<Order> orders = db.loadOrders(customerUsername); // DB filters by username
       java.util.ArrayList<models.Order> orders = db.loadOrders(customerUsername);
       java.text.NumberFormat currency = java.text.NumberFormat.getCurrencyInstance(java.util.Locale.UK);
       
        for (models.Order o : orders)
        { 
            if (o.getUsername().equals(loggedInCustomer.getUsername()))
            { 
                //String line = "Order #" + o.getOrderId() + " - £" + o.getOrderTotal();
                
                //String line = "Order #" + o.getOrderId() + " - " + currency.format(o.getOrderTotal());
                
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                String dateStr = sdf.format(o.getOrderDate());
                String line = "Order #" + o.getOrderId() + " | " + dateStr + " | " + currency.format(o.getOrderTotal());
                model.addElement(line);
            }
        }
        if (model.getSize() == 0)
            {
                model.addElement("No orders found for this customer.");
            }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrders = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstOrders);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setText("Your Orders:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 280, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // FROM ViewOrders to CustomerHome
        // FROM Customer Home Frame to Main Menu Frame
        
        CustomerHome ch = new CustomerHome(loggedInCustomer);
        // get visible the new form
        ch.setVisible(true);
        // hide the current form
        this.setVisible(false);// or this.dispose();
         
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ViewOrders().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstOrders;
    // End of variables declaration//GEN-END:variables
}
